openapi: 3.0.2
components:
  requestBodies:
    PostRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PostRequest'
          examples:
            request:
              $ref: '#/components/examples/PostRequest'
  responses:
    AdminListResult:
      description:  Content returned after successful request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AdminListResult'
          examples:
            response:
              $ref: '#/components/examples/AdminListResult'
    AdminResult:
      description:  Content returned after successful request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AdminResult'
          examples:
            response:
              $ref: '#/components/examples/AdminResult'
  schemas:
    PostRequest:
      type: object
      required:
        - user
        - organization
      properties:
        user:
          type: object
          required:
            - username
          properties:
            username:
              type: string
              description: User name
            first_name:
              type: string
              description: User surname
            last_name:
              type: string
              description: User name
        organization:
          type: integer
          format: int32
          description: Guard company id
        phone_number:
          type: string
          description: Need to add the international area code

    AdminListResult:
      description: Guard admin list
      allOf:
        - $ref: '../common.yaml#/components/schemas/Result'
        - type: object
          properties:
            ret:
              allOf:
                - $ref: '../common.yaml#/components/schemas/Page'
                - type: object
                  properties:
                    results:
                      type: array
                      items:
                        $ref: '#/components/schemas/AdminInfo'
    AdminInfo:
      type: object
      properties:
        user:
          type: object
          properties:
            id:
              type: integer
              format: int32
              description: User id
            username:
              type: string
              description: User name
            first_name:
              type: string
              description: User surname
            last_name:
              type: string
              description: User name
            lang:
              type: string
              description: language
            timezone:
              type: string
              description: The time zone
            activated:
              type: boolean
              enum:
                - true
                - false
            role:
              type: string
              description: User role
        organization:
          type: object
          properties:
            title:
              type: string
              description: Guard company title
            id:
              type: integer
              format: int32
              description: Guard company id
        phone_number:
          type: string
          description: Need to add the international area code

    AdminResult:
      allOf:
        - $ref: '../common.yaml#/components/schemas/Result'
        - type: object
          properties:
            ret:
              $ref: '#/components/schemas/AdminInfo'


  examples:
    PostRequest:
      value:
        user:
          username: guard_admin@turingvideo.net
          last_name: ""
          first_name: ""
        organization: 1
        phone_number: 13111113333

    AdminListResult:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          count: 1
          next: null
          previous: null
          results:
            - user:
                id: 18
                username: guard_admin@turingvideo.net
                last_name: ""
                first_name: ""
                lang: en
                timezone: America/Los_Angeles
                activated: false
                role: guard_admin
              organization:
                title: Nanjing Guard
                id: 1
              phone_number: 13111113333

    AdminResult:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          user:
            id: 18
            username: guard_admin@turingvideo.net
            last_name: ""
            first_name: ""
            lang: en
            timezone: America/Los_Angeles
            activated: false
            role: guard_admin
          organization:
            title: Nanjing Guard
            id: 1
          phone_number: 13111113333
