openapi: 3.0.2

servers:
  - description: Dev
    url: https://dev-gw.turingvideo.cn
info:
  title: Robot API
  version: '1.0'
  license:
    name: TuringVideo
    url: 'https://www.turingvideo.cn'
tags:
  - name: 用户认证
  - name: 基础数据
  - name: 机器人
  - name: 巡检
  - name: 告警事件
security:
  - token: []

paths:

  /auth/:
    post:
      tags:
      - 用户认证
      summary: 登录接口，获取权限
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  description: 登录账户
                password:
                  type: string
                  description: 登录密码
      responses:
        200:
          description: >
            成功认证后，您需要在后续请求中包含此`token`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResult'

  /site/sites:
    get:
      tags:
      - 基础数据
      summary: 获取所属当前用户的站点
      responses:
        200:
          description: 结果返回当前用户所有可用的站点
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SiteInfoPageResult'
              examples:
                response:
                  $ref: '#/components/examples/SiteInfoPageResult'

  /monitor/robot/:
    get:
      tags:
      - 机器人
      summary: 获取当前（站点下）用户所有的机器人信息
      description: 查看指定站点上的所有机器人信息
      parameters:
        - in: query
          name: site_id
          description: 站点ID
          required: false
          schema:
            type: string
      responses:
        200:
          description: Content returned after successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RobotListResult'
              examples:
                response:
                  $ref: '#/components/examples/RobotListResult'

  /robot/robots/{robot_id}:
    get:
      tags:
      - 机器人
      summary: 查看指定机器人信息
      description: |
        查看某个机器人信息（返回机器人信息，电源，状态，位置等）
      parameters:
        - in: path
          name: robot_id
          description: 机器人ID
          required: true
          schema:
            type: string
      responses:
        200:
          description: Content returned after successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RobotResult'
              examples:
                response:
                  $ref: '#/components/examples/Robot'

  /target/targets:
    get:
      tags:
      - 基础数据
      - 巡检
      summary: 巡检点位列表
      description: 有关机器人所有检查点的信息，包括名称，坐标，相应的商店等
      parameters:
        - in: query
          name: site_id
          description: 站点ID
          schema:
            type: integer
        - in: query
          name: name
          description: 巡检点位名称
          schema:
            type: string
        - in: query
          name: serial_no
          description: 序列号，如房间号，资产号等
          schema:
            type: string
        - in: query
          name: floor
          description: 楼层号，`-1`表示`B1`, `1`表示`F1`
          schema:
            type: integer
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/offsetParam'
      responses:
        200:
          description: Content returned after successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TargetPageResult'
              examples:
                response:
                  $ref: '#/components/examples/TargetPageResult'
    post:
      tags:
      - 基础数据
      - 巡检
      summary: 创建新的巡检点位
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - site_id
                - serial_no
                - name
                - floor
                - category
              properties:
                site_id:
                  type: string
                  description: 站点ID
                serial_no:
                  type: string
                  description: 序列号，巡检点位的唯一性
                name:
                  type: string
                  description: |
                    巡检点位名称
                floor:
                  type: string
                  description: |
                    巡检点位的楼层号，`-1`表示`B1`, `1`表示`F1`
                category:
                  type: string
                  description: |
                    巡检点位的类别，如：店铺/多经/吊幔/灯箱
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TargetResult'

  /inspection/inspections:
    get:
      tags:
        - 巡检
      summary: 获取巡检素材列表
      parameters:
        - in: query
          name: robot
          description: 机器人ID
          schema:
            type: string
        - in: query
          name: site
          description: 站点ID
          schema:
            type: integer
            format: int32
        - in: query
          name: target
          description: 巡检点位ID
          schema:
            type: integer
            format: int32
        - in: query
          name: route_id
          description: 巡检路径ID
          schema:
            type: integer
            format: int32
        - in: query
          name: map_id
          description: 巡检地图ID
          schema:
            type: integer
            format: int32
        - in: query
          name: mediums__name
          description: Medium type
          schema:
            type: string
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/offsetParam'
      responses:
        default:
          description: Content returned after successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InspectionPageResult'
              examples:
                response:
                  $ref: '#/components/examples/InspectionPageResult'

  /inspection/inspections/{id}:
    get:
      tags:
        - 巡检
      summary: 获取指定巡检素材信息
      parameters:
        - in: path
          name: id
          required: true
          description: 机器人巡检素材ID
          schema:
            type: integer
            format: int32
      responses:
        default:
          description: Content returned after successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InspectionResult'
              examples:
                response:
                  $ref: '#/components/examples/InspectionResult'

  /config/robot/{robot_id}:
    get:
      tags:
        - 巡检
        - 机器人
      summary: 获取指定机器人的配置信息
      description: 字段`routine`是机器人巡检任务信息
      parameters:
        - in: path
          name: robot_id
          required: true
          description: 机器人ID
          schema:
            type: string
      responses:
        200:
          description: Content returned after successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigResult'
              examples:
                response:
                  $ref: '#/components/examples/ConfigResult'
    put:
      tags:
        - 巡检
        - 机器人
      summary: 更新机器人配置信息
      description: |
        使用`put`方法进行机器人配置的增、删、改操作，（`routines`下是机器人的巡检任务信息）

        `put`入参为`get`接口获取的`result`。
      parameters:
        - in: path
          name: robot_id
          required: true
          description: 机器人ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigInfo'
      responses:
        200:
          description: |
            Content returned after successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigResult'
              examples:
                response:
                  $ref: '#/components/examples/ConfigResult'

  /config/robot/{robot_id}/maps:
    get:
      tags:
        - 巡检
        - 机器人
      summary: 获取指定机器人的所有巡检地图信息
      description: |
        获取该机器人的地图信息（不包含巡检点位信息）
      parameters:
        - in: path
          name: robot_id
          required: true
          description: 机器人ID
          schema:
            type: string
      responses:
        200:
          description: Content returned after successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoutesResult'
              examples:
                response:
                  $ref: '#/components/examples/MapsResult'
  /config/robot/{robot_id}/routes:
    get:
      tags:
        - 巡检
        - 机器人
      summary: 获取指定机器人的所有巡检路径信息
      description: |
        获取该机器人的路径（包含巡检点位信息）
      parameters:
        - in: path
          name: robot_id
          required: true
          description: 机器人ID
          schema:
            type: string
      responses:
        200:
          description: Content returned after successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoutesResult'
              examples:
                response:
                  $ref: '#/components/examples/RoutesResult'
  /monitor/case/:
    get:
      tags:
        - 告警事件
      summary: 机器人告警事件信息
      description: 查看当前用户下机器人告警事件信息
      parameters:
        - $ref: '#/components/parameters/limitParam'
        - in: query
          name: event__site_id
          description: 站点ID
          schema:
            type: integer
            format: int32
        - in: query
          name: status__exclude
          description: |
            需要排除的事件状态
            * `new`: 告警事件刚刚创建，等待处理
            * `viewed`:告警事件被分配给了一名守卫
            * `accepted`: 守卫接受该告警事件
            * `on_the_way`: 守卫准备处理告警事件
            * `arrived`: 守卫到达告警事件地点
            * `Resolved`: 守卫解决了告警事件
            * `notified`: 告警事件发送客户通知
            * `closed`: 告警事件关闭
          schema:
            type: string
            enum:
              - new
              - viewed
              - accepted
              - on_the_way
              - arrived
              - Resolved
              - notified
              - closed
        - in: query
          name: type
          description: 告警事件类型
          schema:
            type: string
            enum:
              - event
              - incident
              - inspection
      responses:
        200:
          description: Content returned after successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CaseListResult'
              examples:
                response:
                  $ref: '#/components/examples/CaseListResult'
  /monitor/case/{id}:
    get:
      tags:
        - 告警事件
      summary: 机器人告警事件信息
      description: 查看当前用户下机器人告警事件信息
      parameters:
        - in: path
          name: id
          required: true
          description: 告警事件实例ID
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: Content returned after successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CaseResult'
              examples:
                response:
                  $ref: '#/components/examples/CaseResult'

components:
  schemas:

    ResponseError:
      type: object
      properties:
        ec:
          type: integer
          description: |
            Respense code（example: `0`）
        em:
          type: string
          description: |
            Respense message（example: `This operation is successful.`、`0`）
        dm:
          type: string
          description: |
            Respense message（example: `ok`）
      description: |
        用户要求返回的信息:
          * 200(0)：This operation is successful.
          * 405(102): Please use a valid method. (method)
          * 400(103): Please submit a valid input. (input)
          * 401(104): Please sign in. (not_in)
          * 403(105)：This operation is forbidden. (forbidden)
          * 409(106)：Invalid email or password. (none)
          * 409(107)：You have no permission. (permission)

    Result:
      type: object
      description: Result
      properties:
        err:
          $ref: '#/components/schemas/ResponseError'

    Page:
      type: object
      description: 请求返回的分页结果
      properties:
        count:
          type: integer
          description: 总数
        next:
          type: string
          description: 下一页的网址
        previous:
          type: string
          description: 前一页的网址

    AuthResult:
      description: 用户登录返回的结果
      allOf:
      - $ref: '#/components/schemas/Result'
      - type: object
        properties:
          ret:
            type: object
            properties:
              token:
                type: string
              expire:
                type: string
                format: date-time
                description: Expiring time in ISO8601 format

    SiteInfo:
      type: object
      properties:
        id:
          type: integer
          description: 站点id
        name:
          type: string
          description: 站点名称
        location:
          type: string
          description: 站点坐标地址
        label:
          type: string
          description: 站点标签
        province:
          type: string
          description: 该站点所在的省
        city:
          type: string
          description: 该站点所在的城市
        county:
          type: string
          description: 该站点所在的县/区

    SiteInfoPageResult:
      description: 网站分页列表
      allOf:
      - $ref: '#/components/schemas/Result'
      - type: object
        properties:
          ret:
            allOf:
            - $ref: '#/components/schemas/Page'
            - type: object
              properties:
                results:
                  type: array
                  items:
                    $ref: '#/components/schemas/SiteInfo'

    Robot:
      type: object
      properties:
        id:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        name:
          type: string
          description: 机器人名称
        status:
          type: string
          enum: [online, offline]
          description: 机器人在线/离线状态
        site_id:
          type: integer
          description: 机器人所属站点ID
        state:
          type: object
          properties:
            status:
              type: string
              description: 机器人在线/离线状态
            power_percentage:
              type: number
              description: 机器人电池电量
            mode:
              type: string
              description: 机器人当前模式

    RobotResult:
      description: 机器人信息
      allOf:
      - $ref: '#/components/schemas/Result'
      - type: object
        properties:
          ret:
            $ref: '#/components/schemas/Robot'

    RobotListResult:
      description: 机器人列表信息
      allOf:
      - $ref: '#/components/schemas/Result'
      - type: object
        properties:
          ret:
            type: array
            items:
              $ref: '#/components/schemas/Robot'

    Target:
      type: object
      properties:
        id:
          type: integer
          description: 机器人巡检点位ID
        site:
          type: integer
          description: 站点ID
        serial_no:
          type: string
          description: 序列号，巡检点位的唯一性
        name:
          type: string
          description: 巡检点位名称
        floor:
          type: integer
          description: |
            巡检点位的楼层号，`-1`表示`B1`, `1`表示`F1`
        longitude:
          type: number
          description: 巡检点位的经度，使用机器人巡逻时需要
        latitude:
          type: number
          description: 巡检点位的纬度，使用机器人巡逻时需要
        desc:
          type: string
          description: 巡检点位信息说明
        category:
          type: string
          description: |
            巡检点位的类别，例如商店，安全通道等
        latest_inspection_time:
          type: string
          description: 系统将自动更新上一次巡逻的时间

    TargetResult:
      description: Result of target
      allOf:
      - $ref: '#/components/schemas/Result'
      - type: object
        properties:
          ret:
            $ref: '#/components/schemas/Target'

    TargetPageResult:
      description: Paged list of targets
      allOf:
      - $ref: '#/components/schemas/Result'
      - type: object
        properties:
          ret:
            allOf:
            - $ref: '#/components/schemas/Page'
            - type: object
              properties:
                results:
                  type: array
                  items:
                    $ref: '#/components/schemas/Target'

    Inspection:
      type: object
      description: 巡检素材对象
      properties:
        id:
          type: integer
          description: 巡检素材ID
          format: int32
        robot_id:
          type: string
          description: 机器人ID
        robot:
          $ref: '#/components/schemas/Robot'
        started_at:
          type: string
          description: 素材开始时间
          format: date-time
        ended_at:
          type: string
          description: 素材结束时间
          format: date-time
        mediums:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                description: 素材文件ID
                format: int32
              name:
                type: string
                description: 素材文件类型：snapshot 图片，video 短视频
                enum: [snapshot, video]
              file:
                type: object
                properties:
                  url:
                    type: string
                    description: 素材文件URL
                  content_type:
                    type: string
                    description: 素材文件类型，如：image/jpeg, video/mp4
                  file_size:
                    type: integer
                    description: 素材文件大小
                  size:
                    type: array
                    items:
                      type: string
                      description: 图片素材的长和宽
                  panoramic:
                    type: boolean
                    description: 是否是全景图片
              inspection_id:
                type: integer
                format: int32
                description: 所属素材ID
        target_id:
          type: integer
          format: int32
          description: 关联巡检对象ID
        site_id:
          type: integer
          format: int32
          description: 关联站点ID
        route_id:
          type: integer
          format: int32
          description: 关联路径ID
        map_id:
          type: integer
          format: int32
          description: 关联地图ID
        target:
          $ref: '#/components/schemas/Target'

    InspectionResult:
      description: 巡检素材返回结果
      allOf:
        - $ref: '#/components/schemas/Result'
        - type: object
          properties:
            ret:
              $ref: '#/components/schemas/Inspection'

    InspectionPageResult:
      description: 巡检素材分页清单
      allOf:
      - $ref: '#/components/schemas/Result'
      - type: object
        properties:
          ret:
            allOf:
            - $ref: '#/components/schemas/Page'
            - type: object
              properties:
                results:
                  type: array
                  items:
                    $ref: '#/components/schemas/Inspection'

    ConfigResult:
      description: 机器人配置信息
      allOf:
        - $ref: '#/components/schemas/Result'
        - type: object
          properties:
            ret:
              $ref: '#/components/schemas/ConfigInfo'
    ConfigInfo:
      type: object
      properties:
        home_cargo_mode:
          type: boolean
          description: 货运模式
          enum:
            - true
            - false
        home_head_angle:
          type: integer
          format: int32
          description: 产地角度
        light_enabled:
          type: boolean
          description: 指示灯是否开启
          enum:
            - true
            - false
        media_alarm_file:
          type: string
          description: 媒体警报文件
        media_background_file:
          type: string
          description: 媒体警报背景文件
        media_speak_message:
          type: string
          description: 媒体警报信息
        power_range_high:
          type: integer
          format: int32
          description: 功率范围最大值
        power_range_low:
          type: integer
          format: int32
          description: 功率范围最小值
        sensor_lidar_enhanced:
          type: boolean
          description: 传感器激光雷达是否增强
          enum:
            - true
            - false
        slam_optimization_interval:
          type: integer
          format: int32
          description: 机器人同时定位和建图的优化间隔
        slam_submap_trim_number:
          type: integer
          format: int32
          description: 机器人同时定位和建图的子图修剪数量
        streaming_hd:
          type: boolean
          description: 视频流是否高清
          enum:
            - true
            - false
        streaming_overlay_map:
          type: boolean
          description: 视频流是否叠加地图
          enum:
            - true
            - false
        enable_nav_update:
          type: boolean
          description: 是否启用导航更新
          enum:
            - true
            - false
        current_map_id:
          type: string
          description: 机器人当前地图的ID
        current_route_id:
          type: integer
          format: int32
          description: 机器人地图当前线路的ID
        streaming_audio_enabled:
          type: boolean
          description: 视频流音频是否启用
          enum:
            - true
            - false
        sensor_enabled:
          type: boolean
          description: 机器人是否使用传感器
          enum:
            - true
            - false
        sensor_types:
          type: string
          description: 机器人传感器类型
        sensor_lidar_model:
          type: string
          description: 机器人传感器激光雷达型号
        way_point_names:
          type: array
          items:
            type: string
            description: Waypoint 路点名称
        routines:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                description: 巡检任务ID
              name:
                type: string
                description: 巡检任务名称
              action:
                type: array
                items:
                  type: object
                  properties:
                    act:
                      type: string
                      description: 机器人举动/行径
                    arg:
                      type: object
                      properties:
                        from_floor:
                          type: integer
                          format: int32
                          description: 机器人进行操作的楼层
                        to_flooor:
                          type: integer
                          format: int32
                          description: 机器人进行操作到达楼层
                        delay_secs:
                          type: integer
                          format: int32
                          description: 延迟时间
                        map_id:
                          type: string
                          format: int32
                          description: 地图ID
                        reset_slam:
                          type: boolean
                          description: 重置机器人同时定位和建图
                          enum:
                            - true
                            - false
                        route_id:
                          type: integer
                          format: int32
                          description: 巡检路径ID
                        rheta:
                          type: number
                          format: double
                        x:
                          type: number
                          format: double
                          description: x坐标点
                        y:
                          type: number
                          format: double
                          description: y坐标点
        lift_trip_id:
          type: integer
          format: int32
          description: 电梯行程ID
        lift_to:
          type: integer
          format: int32
          description: 电梯启动去的楼层
        lift_from:
          type: integer
          format: int32
          description: 电梯从什么楼层启动
        lift_task_id:
          type: integer
          format: int32
          description: 电梯任务ID
        lift_command_id:
          type: integer
          format: int32
          description: 电梯命令ID
        lift_command_type:
          type: string
          description: 电梯命令类型
        lift_status:
          type: string
          description: 电梯状态
        patrol_check_wheel_stuck:
          type: boolean
          description: 巡检检查车轮是否被卡住
          enum:
            - true
            - false
        patrol_linear_speed:
          type: number
          format: float
          description: 巡检速度
        patrol_obstacle_padding:
          type: number
          format: float
          description: 巡检障碍物检测
        patrol_schedule_enabled:
          type: boolean
          description: 巡检时间表是否启用
          enum:
            - true
            - false
        patrol_schedule_end_time:
          type: integer
          format: int32
          description: 巡检结束时间
        patrol_schedule_start_time:
          type: integer
          format: int32
          description: 巡检开启时间
        goal_distance_tolerance_one_loop:
          type: number
          format: float
          description: 巡检一圈目标距离公差
        passed_way_point_ratio:
          type: number
          format: float
          description: 巡检waypoint路点检验通过率
        robot_ids:
          type: array
          items:
            type: string
            description: 机器人ID

    RoutesResult:
      description: 机器人巡检路径信息
      allOf:
        - $ref: '#/components/schemas/Result'
        - type: object
          properties:
            ret:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                    description: 机器人路径ID
                  meta_id:
                    type: string
                  name:
                    type: string
                    description: 机器人路径名称
                  comment:
                    type: string
                    description: 机器人路径描述
                  upload:
                    type: boolean
                    description: 上传开关
                    enum:
                      - true
                      - false
                  upload_status:
                    type: string
                    description: 上传状态
                  delete:
                    type: boolean
                    description: 删除开关
                    enum:
                      - true
                      - false
                  files:
                    type: string
                  signed_files:
                    type: array
                    items:
                      type: object
                      properties:
                        file:
                          type: object
                          properties:
                            file_size:
                              type: integer
                              description: 文件大小
                              format: int32
                            size:
                              type: array
                              items:
                                type: string
                                description: 文件长度和宽度
                            content_type:
                              type: string
                              description: 文件内容类型
                              enum:
                                - image/png
                                - text/pbstream
                                - text/yaml
                            url:
                              type: string
                              description: 文件网址路径
                        type:
                          type: string
                          description: 文件类型
                          enum:
                            - map_png
                            - map_pbstream
                            - map_yaml
                  map_config:
                    type: object
                    properties:
                      resolution:
                        type: number
                        description: 解析度
                        format: float
                      origin:
                        type: array
                        items:
                          type: string
                          description: 机器人地图原点
                      virtual_wall:
                        type: string
                  route:
                    type: object
                    properties:
                      id:
                        type: integer
                        format: int32
                        description: 机器人子路径ID
                      meta_id:
                        type: string
                      name:
                        type: string
                        description: 机器人子路径名称
                      way_points:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              format: int32
                              description: 巡检点位ID
                            name:
                              type: string
                              description: 巡检点位名称
                            actions:
                              type: array
                              items:
                                type: object
                                properties:
                                  act:
                                    type: string
                                    description: 巡检点位需要做的行动
                                    enum:
                                      - snapshot
                                      - video
                                  arg:
                                    type: object
                                    properties:
                                      duration:
                                        type: integer
                                        format: int32
                                        description: 行动持续时间
                                      pitch:
                                        type: number
                                        description: 解析度
                                        format: double
                                      theta:
                                        type: number
                                        description: 解析度
                                        format: double
                                  name:
                                    type: string
                                    description: 巡检点位需要做的行动名
                            isInterpolated:
                              type: boolean
                              enum:
                                - true
                                - false
                            mapId:
                              type: string
                              description: 巡检点位所属地图ID
                            routeId:
                              type: integer
                              format: int32
                              description: 巡检点位ID
                            point:
                              type: object
                              properties:
                                x:
                                  type: number
                                  description: 坐标 x
                                  format: double
                                y:
                                  type: number
                                  description: 坐标 y
                                  format: double
                      robot_ids:
                        type: array
                        items:
                          type: string
                          description: 所属机器人ID
                  elevator_base:
                    type: string
                  calibration:
                    type: string
                  landmarks:
                    type: array
                    items:
                      type: string
                  robot_ids:
                    type: array
                    items:
                      type: string
                      description: 所属机器人ID

    CaseListResult:
      description: 告警事件实例列表
      allOf:
        - $ref: '#/components/schemas/Result'
        - type: object
          properties:
            ret:
              type: object
              properties:
                case:
                  type: array
                  items:
                    $ref: '#/components/schemas/CaseInfo'
                case_stats:
                  $ref: '#/components/schemas/CaseStats'
    CaseResult:
      allOf:
        - $ref: '#/components/schemas/Result'
        - type: object
          properties:
            ret:
              $ref: '#/components/schemas/CaseInfo'

    CaseInfo:
      type: object
      properties:
        id:
          type: string
          description: 告警事件ID
        created_at:
          type: string
          format: date-time
          description: 告警事件创建时间
        updated_at:
          type: string
          format: date-time
          description: 告警事件更新时间
        status:
          type: string
          description: |
            告警事件状态
            * `new`: 告警事件刚刚创建，等待处理
            * `viewed`:告警事件被分配给了一名守卫
            * `accepted`: 守卫接受该告警事件实例
            * `on_the_way`: 守卫准备处理告警事件
            * `arrived`: 守卫到达告警事件地点
            * `Resolved`: 守卫解决了告警事件
            * `notified`: 告警事件发送客户通知
            * `closed`: 告警事件关闭
          enum:
            - new
            - assigned
            - accepted
            - on_the_Way
            - arrived
            - resolved
            - notified
            - closed
        action:
          $ref: '#/components/schemas/Action'
        report:
          type: string
        viewed:
          type: boolean
          enum:
            - true
            - false
          description: 告警事件是否被查看状态
        type:
          type: string
          description: 告警事件类型
          enum:
            - event
            - incident
            - inspection
        priority:
          type: string
          description: 告警事件处理的优先级
          enum:
            - low
            - medium
            - high
            - unassigned
        histories:
          type: array
          description: 告警事件历史记录
          items:
            type: object
            properties:
              id:
                type: integer
                format: int32
                description: 告警事件历史记录ID
              created_at:
                type: string
                format: date-time
              updated_at:
                type: string
                format: date-time
              user_id:
                type: integer
                format: int32
                description: 变更事件状态的用户ID
              action:
                $ref: '#/components/schemas/Action'
        notes:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                format: int32
                description: 告警事件注释ID
              created_at:
                type: string
                format: date-time
              updated_at:
                type: string
                format: date-time
              user_id:
                type: integer
                format: int32
              note:
                type: string
                description: 告警事件注释内容
        inspection_id:
          type: integer
          format: int64
          description: 巡检素材ID
        inspection:
          $ref: '#/components/schemas/Inspection'
    CaseStats:
      type: object
      properties:
        unviewed:
          type: integer
          format: integer
          description: 未查看的告警事件数
        unclosed:
          type: integer
          format: integer
          description: 未关闭的告警事件数
        total:
          type: integer
          format: integer
          description: 告警事件总数
    Action:
      type: string
      description: |
        操作员/守卫执行的操作
        * `new`: 默认动作
        * `viewed`: 告警事件已被操作员查看
        * `false_alarm`: 这是一个假的告警事件
        * `no_harm`: 告警事件不是误报，但是实际上是告警安全的
        * `call_police`: 告警事件需要报警
        * `dispatch_guard`: 告警事件需要派遣守卫
        * `update_priority`: 更新告警事件实例优先级
        * `dispatch_robot`: 派遣机器人处理告警事件
        * `accept_case`: 更新了告警事件状态
        * `start`: 守卫开始处理告警事件
        * `arrive`: 守卫到达告警事件地点
        * `resolve_case`: 守卫解决了告警事件
        * `add_note`: 操作员为告警事件添加注释
        * `close`: 告警事件关闭
        * `update_types`: 操作员更新了告警事件类型
        * `notify_customer`: 告警事件通知客户
      enum:
        - new
        - viewed
        - false_alarm
        - no_harm
        - call_police
        - dispatch_guard
        - update_priority
        - dispatch_robot
        - accept_case
        - start
        - arrive
        - resolve_case
        - add_note
        - close
        - update_types
        - notify_customer
  examples:

    RobotListResult:
      value:
        err:
          ec: 0
          em: ok
          dm: ok
        ret:
          - id: robot_dog_sr_20014
            created_at: 2020-03-05T20:52:03.716598Z
            updated_at: 2020-05-15T04:14:00.019909Z
            name: Dev 14
            status: offline
            state:
              mode: ""
              power_percentage: null
              status: robot_offline
            site_id: 16

    SiteInfoPageResult:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          count: 1
          next: null
          previous: null
          results:
            - id: 16
              name: wanda-site-test-1
              location: Beijing
              label: 万达测试站点
              province: 北京
              city: 北京
              county: 通州

    Robot:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          id: robot_dog_sr_20014
          created_at: 2020-03-05T20:52:03.716598Z
          updated_at: 2020-05-15T04:14:00.019909Z
          name: Dev 14
          status: offline
          state:
            mode: ""
            power_percentage: null
            status: robot_offline
          site_id: 16

    TargetPageResult:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          count: 1
          next: null
          previous: null
          results:
            - id: 3
              site: 2
              serial_no: 5-312
              name: 办公室
              floor: 3
              longitude: '116.397128'
              latitude: '39.916527'
              desc: ''
              category: ''
              latest_inspection_time: '2019-08-16T09:15:22Z'

    InspectionResult:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          id: 184
          robot_id: robot_dog_sr_20002
          robot:
            id: robot_dog_sr_20002
            name: 仓库巡逻号
            type: test_li
          started_at: 2019-10-17T07:01:14Z
          ended_at: 2019-10-17T07:01:14Z
          mediums:
            - id: 185
              name: snapshot
              file:
                size:
                  - 1920
                    1080
                content_type: image/jpeg
                file_size: 528447
                url: https://wanda-poc.s3.cn-northwest-1.amazonaws.com
              inspection_id: 184
          target_id: 3
          site_id: null
          route_id: 1
          map_id: 2
          target:
            id: 3
            site: 2
            serial_no: 5-312
            name: 办公室
            floor: 3
            longitude: '116.397128'
            latitude: '39.916527'
            desc: ''
            category: ''
            latest_inspection_time: '2019-08-16T09:15:22Z'

    InspectionPageResult:
      value:
        err:
          ec: 0
          em: This operation is successful.
          dm: ok
        ret:
          count: 1
          next: null
          previous: null
          results:
            - id: 184
              robot_id: robot_dog_sr_20002
              robot:
                id: robot_dog_sr_20002
                name: 20002
                type: test_li
              started_at: 2019-10-17T07:01:14Z
              ended_at: 2019-10-17T07:01:14Z
              mediums:
                - id: 185
                  name: snapshot
                  file:
                    size:
                      1920
                      1080
                    content_type: image/jpeg
                    file_size: 528447
                    url: https://wanda-poc.s3.cn-northwest-1.amazonaws.com.cn/users/2/robots/wx

    ConfigResult:
      value:
        err:
          ec: 0
          em: ok
          dm: ok
        ret:
          home_cargo_mode: false
          home_head_angle: 0
          light_enabled: false
          media_alarm_file: alarm.mp3
          media_background_file: bg.mp3
          media_speak_message:
          power_range_high: 90
          power_range_low: 30
          sensor_lidar_enhanced: true
          slam_optimization_interval: 15
          slam_submap_trim_number: 12
          streaming_hd: true
          streaming_overlay_map: false
          enable_nav_update: true
          current_map_id: robot_dog_sr_20020.1590546545353
          current_route_id: 1590558781758
          streaming_audio_enabled: false
          sensor_enabled: true
          sensor_types: g5stpatrol_performance
          sensor_lidar_model: S1
          way_point_names: []
          routines:
            - id: 1589202954571
              name: 全自动店铺巡检
              action:
                - act: leave_home
                  arg: {}
                - act: take_elevator
                  arg:
                    from_floor: 1
                    to_flooor: 2
                - act: load_map_route
                  arg:
                    delay_secs: 2
                    map_id: robot_dog_sr_20020.1590546545352
                    reset_slam: true
                    route_id: 1589202954331
                    rheta: -2.8966139904629244
                    x: -45.83862361370879
                    y: 56.25018576088915
          lift_trip_id: ''
          lift_to: 0
          lift_from: 0
          lift_task_id: ''
          lift_command_id: ''
          lift_command_type: ''
          lift_status: ''
          patrol_check_wheel_stuck: false
          patrol_linear_speed: 0.7
          patrol_obstacle_padding: 0.42
          patrol_schedule_enabled: false
          patrol_schedule_end_time: 0
          patrol_schedule_start_time: 0
          goal_distance_tolerance_one_loop: 0.5
          passed_way_point_ratio: 0.3
          robot_ids:
            - robot_dog_sr_20020

    RoutesResult:
      value:
        value:
          err:
            ec: 0
            em: ok
            dm: ok
          ret:
            id:  'robot_dog_sr_20020.1589509647283'
            meta_id:  'robot_dog_sr_20020::map::robot_dog_sr_20020.1589509647283'
            name:  '新建地图 2020-05-15 02:28:16'
            comment: ''
            upload: false
            upload_status:  finished
            delete: false
            files: null
            signed_files:
              - file:
                  file_size: 15595
                  size:
                    - 303
                    - 317
                  content_type:  image/png
                  url:  https://dev-data-fo
                  type:  map_png
              - file:
                  file_size: 606602
                  size: null
                  content_type:  text/pbstream
                  url:  https://dev-data-fo
                  type:  map_pbstream
              - file:
                  file_size: 208
                  size: null
                  content_type:  text/yaml
                  url:  https://dev-data-fo
                type:  map_yaml
            map_config:
              resolution: 0.04
              origin:
                - '-5.8'
                - '-8.28'
              virtual_wall: null
            route:
              id:  1589509790549
              name:  '新建路线 2020-05-15 02:31:25'
              meta_id:  'robot_dog_sr_20020::route::robot_dog_sr_20020.1589509647283::1589509790549'
              way_points:
                - id: 1589509799458
                  name:
                  actions:
                    - act:  snapshot
                      arg:
                        duration: 0
                        pitch: 0.0036440939
                        theta: -2.0937453135848045
                      name: ''
                  isInterpolated: false
                  mapId:  'robot_dog_sr_20020.1589509647283'
                  routeId:  1589509790549
                  point:
                    x: '-2.0111198726356423'
                    y: '0.600399600638084'
              robot_ids:
                - robot_dog_sr_20020
            elevator_base: null
            calibration: null
            landmarks: []
            robot_ids:
              - robot_dog_sr_20020
    MapsResult:
      value:
        value:
          err:
            ec: 0
            em: ok
            dm: ok
          ret:
            id:  'robot_dog_sr_20020.1589509647283'
            meta_id:  'robot_dog_sr_20020::map::robot_dog_sr_20020.1589509647283'
            name:  '新建地图 2020-05-15 02:28:16'
            comment: ''
            upload: false
            upload_status:  finished
            delete: false
            files: null
            signed_files:
              - file:
                  file_size: 15595
                  size:
                    - 303
                    - 317
                  content_type:  image/png
                  url:  https://dev-data-fo
                  type:  map_png
              - file:
                  file_size: 606602
                  size: null
                  content_type:  text/pbstream
                  url:  https://dev-data-fo
                  type:  map_pbstream
              - file:
                  file_size: 208
                  size: null
                  content_type:  text/yaml
                  url:  https://dev-data-fo
                type:  map_yaml
            map_config:
              resolution: 0.04
              origin:
                - '-5.8'
                - '-8.28'
              virtual_wall: null
            route: null
            elevator_base: null
            calibration: null
            landmarks: []
            robot_ids:
              - robot_dog_sr_20020

    CaseListResult:
      value:
        err:
          ec:0
          em:ok
          dm:ok
        ret:
          cases:
            - id: 3631
              created_at: '2020-06-10T12:13:57.701132Z'
              updated_at: '2020-06-10T12:13:57.701164Z'
              status: new
              action: new
              report: ''
              viewed: false
              type: event
              priority: unassigned
              histories: null
              notes: null
              inspection_id: 0
              inspection: null
        case_stats:
          unviewed: 160
          unclosed: 170
          total: 170
    CaseResult:
      value:
        err:
          ec:0
          em:ok
          dm:ok
        ret:
          id: 3631
          created_at: '2020-06-10T12:13:57.701132Z'
          updated_at: '2020-06-10T12:13:57.701164Z'
          status: new
          action: new
          report: ''
          viewed: false
          type: event
          priority: unassigned
          histories: null
          notes: null
          inspection_id: 0
          inspection: null
  parameters:
    limitParam:
      in: query
      name: limit
      description: 每页最大数量
      schema:
        type: integer
        format: int32
    offsetParam:
      in: query
      name: offset
      description: Query offset
      schema:
        type: integer
        format: int32

  securitySchemes:
    token:
      type: apiKey
      in: header
      name: Authorization
